//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSimSniffer.Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InSimSniffer.Library.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string LookupFlagBlue {
            get {
                return ResourceManager.GetString("LookupFlagBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string LookupFlagYellow {
            get {
                return ResourceManager.GetString("LookupFlagYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground.
        /// </summary>
        internal static string LookupHlvcGround {
            get {
                return ResourceManager.GetString("LookupHlvcGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LookupHlvcNone {
            get {
                return ResourceManager.GetString("LookupHlvcNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speeding.
        /// </summary>
        internal static string LookupHlvcSpeeding {
            get {
                return ResourceManager.GetString("LookupHlvcSpeeding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string LookupHlvcWall {
            get {
                return ResourceManager.GetString("LookupHlvcWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string LookupHostGuest {
            get {
                return ResourceManager.GetString("LookupHostGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string LookupHostHost {
            get {
                return ResourceManager.GetString("LookupHostHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPR.
        /// </summary>
        internal static string LookupMprMpr {
            get {
                return ResourceManager.GetString("LookupMprMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPR.
        /// </summary>
        internal static string LookupMprSpr {
            get {
                return ResourceManager.GetString("LookupMprSpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string LookupOffOnOff {
            get {
                return ResourceManager.GetString("LookupOffOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string LookupOffOnOn {
            get {
                return ResourceManager.GetString("LookupOffOnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string LookupPausedPaused {
            get {
                return ResourceManager.GetString("LookupPausedPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LookupRaceInProgNone {
            get {
                return ResourceManager.GetString("LookupRaceInProgNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qual.
        /// </summary>
        internal static string LookupRaceInProgQual {
            get {
                return ResourceManager.GetString("LookupRaceInProgQual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string LookupRaceInProgRace {
            get {
                return ResourceManager.GetString("LookupRaceInProgRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        internal static string LookupUcidHost {
            get {
                return ResourceManager.GetString("LookupUcidHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string LookupWeatherClear {
            get {
                return ResourceManager.GetString("LookupWeatherClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overcast.
        /// </summary>
        internal static string LookupWeatherOvercast {
            get {
                return ResourceManager.GetString("LookupWeatherOvercast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        internal static string LookupWeatherSunset {
            get {
                return ResourceManager.GetString("LookupWeatherSunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string LookupWindHigh {
            get {
                return ResourceManager.GetString("LookupWindHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LookupWindLow {
            get {
                return ResourceManager.GetString("LookupWindLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string LookupWindNone {
            get {
                return ResourceManager.GetString("LookupWindNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received packet is not multiple of four..
        /// </summary>
        internal static string TcpSocketCorruptPacketExceptionMessage {
            get {
                return ResourceManager.GetString("TcpSocketCorruptPacketExceptionMessage", resourceCulture);
            }
        }
    }
}
