//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InSimSniffer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InSimSniffer.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutDialogVersion {
            get {
                return ResourceManager.GetString("AboutDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pining for the fjords!?.
        /// </summary>
        internal static string AboutFishDanceExceptionMessage {
            get {
                return ResourceManager.GetString("AboutFishDanceExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogCultureText {
            get {
                return ResourceManager.GetString("ExceptionDialogCultureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogDateText {
            get {
                return ResourceManager.GetString("ExceptionDialogDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogExceptionText {
            get {
                return ResourceManager.GetString("ExceptionDialogExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogInnerExceptionText {
            get {
                return ResourceManager.GetString("ExceptionDialogInnerExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogMessageText {
            get {
                return ResourceManager.GetString("ExceptionDialogMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogOSText {
            get {
                return ResourceManager.GetString("ExceptionDialogOSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogSourceText {
            get {
                return ResourceManager.GetString("ExceptionDialogSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogStackTraceText {
            get {
                return ResourceManager.GetString("ExceptionDialogStackTraceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogTargetText {
            get {
                return ResourceManager.GetString("ExceptionDialogTargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}{1}.
        /// </summary>
        internal static string ExceptionDialogVersionText {
            get {
                return ResourceManager.GetString("ExceptionDialogVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExceptionLogFailedDialogMessage {
            get {
                return ResourceManager.GetString("ExceptionLogFailedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Log Error.
        /// </summary>
        internal static string ExceptionLogFailedDialogTitle {
            get {
                return ResourceManager.GetString("ExceptionLogFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The log file &apos;{0} has been written.
        /// </summary>
        internal static string ExceptionLogSuccessDialogMessage {
            get {
                return ResourceManager.GetString("ExceptionLogSuccessDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Exported Sucessfully.
        /// </summary>
        internal static string ExceptionLogSuccessDialogTitle {
            get {
                return ResourceManager.GetString("ExceptionLogSuccessDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eXtensible Markup Language File (*.xml)|*.xml|Plain Text File (*.txt)|*.txt|InSimSniffer Data File (*.sniffer)|*.sniffer.
        /// </summary>
        internal static string ExportDialogFilter {
            get {
                return ResourceManager.GetString("ExportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Packets.
        /// </summary>
        internal static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ExportErrorDialogMessage {
            get {
                return ResourceManager.GetString("ExportErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Error.
        /// </summary>
        internal static string ExportErrorDialogTitle {
            get {
                return ResourceManager.GetString("ExportErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension {0} is not supported.
        /// </summary>
        internal static string ExportExtensionNotSupportedMessage {
            get {
                return ResourceManager.GetString("ExportExtensionNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSimSniffer Export {0}.
        /// </summary>
        internal static string ExportFileName {
            get {
                return ResourceManager.GetString("ExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export file &apos;{0}&apos; has been written.
        /// </summary>
        internal static string ExportSuccessDialogMessage {
            get {
                return ResourceManager.GetString("ExportSuccessDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Successfully Completed.
        /// </summary>
        internal static string ExportSuccessDialogTitle {
            get {
                return ResourceManager.GetString("ExportSuccessDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Filter Packets&gt;.
        /// </summary>
        internal static string FilterDefaultString {
            get {
                return ResourceManager.GetString("FilterDefaultString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSimSniffer Data File (*.sniffer)|*.sniffer.
        /// </summary>
        internal static string ImportDialogFilter {
            get {
                return ResourceManager.GetString("ImportDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Packets.
        /// </summary>
        internal static string ImportDialogTitle {
            get {
                return ResourceManager.GetString("ImportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ImportErrorDialogMessage {
            get {
                return ResourceManager.GetString("ImportErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Error.
        /// </summary>
        internal static string ImportErrorDialogTitle {
            get {
                return ResourceManager.GetString("ImportErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid header in import file &apos;{0}&apos;.
        /// </summary>
        internal static string ImportInvalidHeaderErrorMessage {
            get {
                return ResourceManager.GetString("ImportInvalidHeaderErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version in import file &apos;{0}&apos;.
        /// </summary>
        internal static string ImportInvalidVersionErrorMessage {
            get {
                return ResourceManager.GetString("ImportInvalidVersionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported {0} packet(s).
        /// </summary>
        internal static string ImportSuccessStatusMessage {
            get {
                return ResourceManager.GetString("ImportSuccessStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSim connection closed.
        /// </summary>
        internal static string InSimDisconnectedStatusMessage {
            get {
                return ResourceManager.GetString("InSimDisconnectedStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string InSimErrorDialogMessage {
            get {
                return ResourceManager.GetString("InSimErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSim Error.
        /// </summary>
        internal static string InSimErrorDialogTitle {
            get {
                return ResourceManager.GetString("InSimErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to LFS!.
        /// </summary>
        internal static string InSimInitializedStatusMessage {
            get {
                return ResourceManager.GetString("InSimInitializedStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure LFS is running and configured to accept connections at address {0}:{1}.
        /// </summary>
        internal static string InSimInitializeFailedDialogMessage {
            get {
                return ResourceManager.GetString("InSimInitializeFailedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSim Connection Failed.
        /// </summary>
        internal static string InSimInitializeFailedDialogTitle {
            get {
                return ResourceManager.GetString("InSimInitializeFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InSim connection failed.
        /// </summary>
        internal static string InSimInitializeFailedStatusMessage {
            get {
                return ResourceManager.GetString("InSimInitializeFailedStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to connect....
        /// </summary>
        internal static string InSimInitializingStatusMessage {
            get {
                return ResourceManager.GetString("InSimInitializingStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to InSim.
        /// </summary>
        internal static string InSimLostNotifyMessage {
            get {
                return ResourceManager.GetString("InSimLostNotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to InSim.
        /// </summary>
        internal static string InSimLostStatusMessage {
            get {
                return ResourceManager.GetString("InSimLostStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string InSimPausedStatusMessage {
            get {
                return ResourceManager.GetString("InSimPausedStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpaused.
        /// </summary>
        internal static string InSimUnpausedStatusMessage {
            get {
                return ResourceManager.GetString("InSimUnpausedStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-connect failed as cannot determin if LFS has started. This is probably because LFS is set to Run as Adminstrator. Would you like to connect to LFS now?.
        /// </summary>
        internal static string LaunchLfsAutoConnectFailedDialogMessage {
            get {
                return ResourceManager.GetString("LaunchLfsAutoConnectFailedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Connect Failed.
        /// </summary>
        internal static string LaunchLfsAutoConnectFailedDialogTitle {
            get {
                return ResourceManager.GetString("LaunchLfsAutoConnectFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string LaunchLfsFailedDialogErrorMessage {
            get {
                return ResourceManager.GetString("LaunchLfsFailedDialogErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the location of LFS.exe is correctly set in the options.
        /// </summary>
        internal static string LaunchLfsFailedDialogMessage {
            get {
                return ResourceManager.GetString("LaunchLfsFailedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch LFS Failed.
        /// </summary>
        internal static string LaunchLfsFailedDialogTitle {
            get {
                return ResourceManager.GetString("LaunchLfsFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Connected].
        /// </summary>
        internal static string MainFormTitleConnected {
            get {
                return ResourceManager.GetString("MainFormTitleConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Connected] - [{1}].
        /// </summary>
        internal static string MainFormTitleHostName {
            get {
                return ResourceManager.GetString("MainFormTitleHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [Paused].
        /// </summary>
        internal static string MainFormTitlePaused {
            get {
                return ResourceManager.GetString("MainFormTitlePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is hidden, but still running in the background.
        /// </summary>
        internal static string MinimizedToTrayNotifyMessage {
            get {
                return ResourceManager.GetString("MinimizedToTrayNotifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live for Speed Executable File (LFS.exe)|LFS.exe.
        /// </summary>
        internal static string OptionsLfsExeBrowseDialogFilter {
            get {
                return ResourceManager.GetString("OptionsLfsExeBrowseDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate LFS.exe.
        /// </summary>
        internal static string OptionsLfsExeBrowseDialogTitle {
            get {
                return ResourceManager.GetString("OptionsLfsExeBrowseDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string RequestFailedDialogMessage {
            get {
                return ResourceManager.GetString("RequestFailedDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0} Failed.
        /// </summary>
        internal static string RequestFailedDialogTitle {
            get {
                return ResourceManager.GetString("RequestFailedDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a UVal:.
        /// </summary>
        internal static string RequestSmallDialogCaption {
            get {
                return ResourceManager.GetString("RequestSmallDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request {0}.
        /// </summary>
        internal static string RequestSmallDialogTitle {
            get {
                return ResourceManager.GetString("RequestSmallDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string StartupCriticalErrorDialogMessage {
            get {
                return ResourceManager.GetString("StartupCriticalErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error!.
        /// </summary>
        internal static string StartupCriticalErrorDialogTitle {
            get {
                return ResourceManager.GetString("StartupCriticalErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is available, do you want to go to the download page?.
        /// </summary>
        internal static string UpdateAvailableDialogMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailableDialogTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string UpdateErrorDialogMessage {
            get {
                return ResourceManager.GetString("UpdateErrorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        internal static string UpdateErrorDialogTitle {
            get {
                return ResourceManager.GetString("UpdateErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data received on version check.
        /// </summary>
        internal static string UpdateInfoDownloadErrorMessage {
            get {
                return ResourceManager.GetString("UpdateInfoDownloadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no updates at this time.
        /// </summary>
        internal static string UpdateNotAvailableDialogMessage {
            get {
                return ResourceManager.GetString("UpdateNotAvailableDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update Available.
        /// </summary>
        internal static string UpdateNotAvailableDialogTitle {
            get {
                return ResourceManager.GetString("UpdateNotAvailableDialogTitle", resourceCulture);
            }
        }
    }
}
